os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
sudo: required
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - sudo usermod -a -G docker $USER
  - docker pull fr3akyphantom/droid-builder:focal
before_script:
  - cd $HOME && mkdir twrp
  - |
    docker run --privileged --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$HOME:/home/builder:rw,z" -v "$HOME/.ccache:/srv/ccache:rw" fr3akyphantom/droid-builder:focal bash << EOF
    ls -l
    cd /home
    ls -l
    cd /builder
    ls -l
    cd /twrp
    exit
    EOF
  - TWRP_SOURCE1="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.aa" && TWRP_SOURCE2="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ab" && TWRP_SOURCE3="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ac" && TWRP_SOURCE4="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ad"
  # Then uncomment below lines to download & extract the multi-part files
  - wget -q --show-progress --progress=bar:force "${TWRP_SOURCE1}" "${TWRP_SOURCE2}" "${TWRP_SOURCE3}" "${TWRP_SOURCE4}"
  - cat MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.a* > MinimalOmni.tzst
  - tar --zstd -xf MinimalOmni.tzst --directory $HOME/twrp/
  - rm MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.*
script:
  # Replace your ${_USERNAME_}, ${_REPO_SLUG_}, ${_VENDORNAME_}, ${_CODENAME_}
  - cd $HOME/twrp/ && git clone https://github.com/Sam-1210/android_device_xiaomi_santoni.git device/xiaomi/santoni
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - |
    docker run --privileged --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$HOME:/home/builder:rw,z" -v "$HOME/.ccache:/srv/ccache:rw" fr3akyphantom/droid-builder:focal bash << EOF
    ls -l
    cd /home
    ls -l
    cd /builder
    ls -l
    cd /twrp
    source build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
    BUILD_FLAVOR="eng"
    lunch omni_santoni-${BUILD_FLAVOR}
    make -j$(nproc --all) recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/santoni/recovery.img $HOME/twrp/TWRP-$version-santoni-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-${_CODENAME_}-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
    repo: Sam-1210/android_device_xiaomi_santoni # Optional: If you want to deploy on different repository
    branch: main # Optional: Needs to be exact as the config branch
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
